### ISSUE TITLE
Check is a provider is currently being listened

### ISSUE THREAD

**Issue by tzvc** [rrousselGit/riverpod#1056]
I'd love to have a way to check if a provider is currently being listened in the tree.

An example use-case for this is a problem I had recently:

I have a family `ChangeNotifierProvider` which, given a user ID, load that user from my API and expose methods to change the state of that user client-side. 

I use this provider everytime I display a user's info in my app.

So if let's say I upvote this user's post in my app, i can do 
```dart
context.read(userProvider(<post-author-id>)).addReputation(1);
```
To update this user's reputation UI instantly without having to refresh.

This is all well and good but, I have no way of telling if something is actually listening to that provider. If not, I don't want to create it thus saving a unnecessary API call to fetch this user's data.

What I've considered so far is finding a way to check if the provider exists (in the ProviderScope?) but this seems hacky at best.

Is there a way to do that ? And is it even at all a valid use-case ?

**Comment by rrousselGit** [comment]
But how/why does your UI allows modifying a user if that user is not yet available?

**Comment by Wishmater** [comment]
I have a different use-case that could make use of this feature.

Say I have a provider that fetches a list of all users with all their info.

Then I have another provider family that fetches a specific user's info given its id. In this second provider it would be better to check if the first one was already called, if it was, just get the requested user info from the list, if it was not, make an API call requesting only the specified user's info, not the entire list.

There could even be more advanced use-cases that require knowing the current state of a provider, I think it would be a nice feature to add.

**Comment by rrousselGit** [comment]
@Wishmater  you should be able to achieve the same behavior by making a third provider

This provider would first check the list of all users for the presence the User with a specific ID. Then if absent, it'd do the fetching using the other provider (the family one).

**Comment by rrousselGit** [comment]
@Wishmater  what would happen in your case if suddenly the list of all users is fetched, when the provider that fetches a single user already had completed?

**Comment by Wishmater** [comment]
> what would happen in your case if suddenly the list of all users is fetched, when the provider that fetches a single user already had completed?

Interesting, ideally checking if a provider was already called shouldn't make you watch that provider. So if at the time of fetching a single user the list wasn't called, and it completed by fetching that user directly, it should not care what happens to the list provider after, since the answer doesn't depend on it.

What I imagine is something like this:

`
if (ref.isActive(listProvider)) {
   return ref.watch(listProvider).firstWhere((e)=>e.id==userId));
} else {
   return API.fetchUser(userId);
}
`

So, in this way, the list provider is only watched if it was already called at the time of calling the single user provider.

**Comment by rrousselGit** [comment]
But if the create function was re-executed _after_ the listProvider was initialized, then the result of this other provider would be different

That's something I would like to avoid. Riverpod is currently deterministic. There's never a case where if you manually re-executed a provider, its behavior would be different (or then that's a bug in your code)

**Comment by Wishmater** [comment]
I understand, but giving the developer the ability to define multiple possible sources for certain data, and the ability to choose the appropriate source for each context could drastically improve performance in some cases. Of course, it is the developer's responsability to make sure the returned value will be the same for all sources, and if this is true, it ultimately doesn't matter if it was obtained from a different source when refreshed, because the returned value is the same.

**Comment by rrousselGit** [comment]
For now I don't find the arguments for this convincing. I'd fear that the downsides would outweigh the benefits


The problem with this issue is that it's describing a solution, not the problem that we want to solve.
I don't agree with the solution proposed, but maybe we could solve the associated problem differently.


I'm going to close this for now. If someone feels that this is an important issue, I'd encourage them to open a new issue specific to the problem, not the solution.

**Comment by rrousselGit** [comment]
With 2.1.0, you will now be able to do:

```dart
ref.exists(provider);
container.exists(provider);
widgetRef.exists(provider);
```
