### ISSUE TITLE
Ref/WidgetRef should implement AnyRef to expose common functionality

### ISSUE THREAD

**Issue by ciriousjoker** [rrousselGit/riverpod#1390]
**Is your feature request related to a problem? Please describe.**

We want to accept either a `Ref` or a `WidgetRef` as a parameter of a function. We only need to use its `.read()` and `.watch()` methods, which are identical.

**Describe the solution you'd like**
We'd like to accept a parameter of type `AnyRef` that only exposes common functionality between different refs.

**Describe alternatives you've considered**
We could declare multiple functions, one for each ref type, but that's verbose.

**Additional context**
N/A

**Comment by rrousselGit** [comment]
They voluntarily do not share the same interface.

You should not use them interchangeably. You probably should refactor your functions to always take a Ref (as in never a WidgetRef).

**Comment by Numoy** [comment]
But why? Both classes have basically the same contract why shouldn't there be a common base class?
(Another use-case would be extension methods -> With the current solution we have to apply it on both)

**Comment by rrousselGit** [comment]
They don't have the same contract
They _look_ the same but have differences.

To begin with, there aren't 2 but 3 Ref-like objects. ProviderContainer uses that "contract" too:

```dart
container.listen(provider, onChange);
container.read(provider);
```

(but does not have a `watch`)


A function that uses either Ref or WidgetRef is not the correct abstraction.
Either you should make a new provider, or make a new modifier (like `.select` / `.notifier`)

Such that you end-up with:

```dart
ref.watch(yourThing)
widgetRef.watch(yourThing)
```

instead of:

```dart
yourThing(ref)
yourThing(widgetRef)
```
