### ISSUE TITLE
mounted property on ConsumerWidget

### ISSUE THREAD

**Issue by vandadnp** [rrousselGit/riverpod#1579]
Hi and thank you for Riverpod. I appreciate all the hard work that has gone into creating this library.

When performing navigation across async gaps, I would have wanted to be able to continue using `ConsumerWidget` rather than `ConsumerStatefulWidget` since, from what I understand, `ConsumerWidget` is in fact a stateful widget! However, at the moment `ConsumerWidget` does not expose a `mounted` property which can be checked before doing navigation across async gaps.

It would be really good if `ConsumerWidget` could expose a getter called `mounted` which could be used for navigation across async gaps.

Thank you again for Riverpod and for your time,
/v

**Comment by rrousselGit** [comment]
Hello!

ConsumerWIdget extends StatefulWidget for the sole reason of having two parameters on `build`. Otherwise it'd extend StatelessWidget

But in any case, what you're asking isn't possible. ConsumerWidget is still a Widget, not a State. There's no way to pass the `mounted` property there.

And even if we could do that, I probably wouldn't do it. I'd instead suggest asking Flutter to add one for StatelessWidget (as ConsumerWidget as similar constraints to that of StatelessWidget). I'd then add it to ConsumerWidget

**Comment by vandadnp** [comment]
Hi Remi and thank you for your response. I agree that it probably needs to go all the way down to the Flutter team hence this issue won't belong here in this repo anymore. Thank you for your time and I'll take the liberty of closing this issue. Have a good rest of the day. /v
