### ISSUE TITLE
If a FutureProvider fails, ProviderObserver should receive a providerDidFail event with the error/stacktrace

### ISSUE THREAD

**Issue by rrousselGit** [rrousselGit/riverpod#1580]
It's a bit weird that AsyncErrors are received as "valid data" in the observer

**Comment by jamescardona11** [comment]
Hello @rrousselGit 
Probably this error it's a big error, but I tryed to fix it. I'm work on understanding the codebase of riverpod for the last week.

I found the posible cause of this error, but I don't know if I'm right:
To test I used marvel example and throw an error in the 'characterPages' future, and create a simple logger with ProviderObserver, following the official documentation.

In the file element.dart in the next method I found the possible error.

`@protected
  void setState(State newState) 
  ...
`

When AsyncError arrive here like a **newState**, the method set a `ResultData(newState)` for **_state** and **result**; after do it, provider loss the AsyncError, and for that reason ProviderObserver can't trigger providerDidFail.

Two ideas to solve this:

1) Uncompleted solution.
Create an **ResultError(newState.error, newState.stackTrace)** and set to **_state** and **result** when the coming **newState** is and error.
What is the issue?,  Provider.watch throw and _UncontrolledProviderScopeElement and, never finish the loading  because the state it's an uncatched error.

![Screen Shot 2022-08-24 at 10 52 27 PM](https://user-images.githubusercontent.com/65878592/186570791-f2c9d0ea-2752-4807-a0eb-acd48b70d362.png)



2)
Set **ResultData** to **_setState** and ResultError to **result**.
`_state = ResultData(newState);

    final Result<State> result = 
        ? ResultError(newState.error, newState.stackTrace)
        : ResultData(newState);`
![Screen Shot 2022-08-24 at 10 51 48 PM](https://user-images.githubusercontent.com/65878592/186570696-9071d54a-0939-4d39-8063-ae05e1d0e8ae.png)

With this works fine. I don't know if this is the solution. It's a strange that **result** and **_state** have different types of data to works.

I keep working on understanding riverpod.
Let me know if I am wrong or If this is a possible solution, if it's a possible solution I can make the unit-testing and other things to help you.

Regards

**Comment by rrousselGit** [comment]
You've definitely found the correct places

We can't really use ResultError though. That would cause `ref.read(provider)` to throw instead of returning AsyncError.

Instead we probably need a way to tell `notifyListeners` that the new state is an error state.

**Comment by josh-burton** [comment]
Just ran into this issue I think. I seem to have providers failing due to watching a futureprovider that fails,  but nothing is  being reported by my provider observer.

Is the current fix to wrap in a try catch?

**Comment by rrousselGit** [comment]
Check values where the value is an AsyncError

**Comment by lucavenir** [comment]
@josh-burton There's a good chance that your failing `FutureProvider` _is_ reporting that to your observer, but in its `didUpdateProvider` method.

If I may, here's a workaround while we wait for this breaking change to be eventually implemented (or further discussed?).

```dart
// class ProviderObserver... blah blah
final Logger _logger;

@override
void didUpdateProvider(
  ProviderBase<Object?> provider,
  Object? previousValue,
  Object? newValue,
  ProviderContainer container,
) {
  if (newValue is AsyncError) {  // handle this special case
    return _handleError(
      provider,
      newValue.error,
      newValue.stackTrace,
    );
  }

  _logger  // "normal" logging logic
    ..finest('$provider updated')
    ..finest('\tOld value: $previousValue')
    ..finest('\tNew value: $newValue');
}

// or your custom logic here
void _handleError(
  ProviderBase<Object?> provider,
  Object error,
  StackTrace stackTrace,
) {
  _logger
    ..severe('$provider raised an Exception')
    ..severe('\tError: $error')
    ..severe('\tStack Trace: $stackTrace');
}
```

**Comment by josh-burton** [comment]
> @josh-burton There's a good chance that your failing `FutureProvider` _is_ reporting that to your observer, but in its `didUpdateProvider` method.
> 
> If I may, here's a workaround while we wait for this breaking change to be eventually implemented (or further discussed?).
> 
> ```dart
> // class ProviderObserver... blah blah
> final Logger _logger;
> 
> @override
> void didUpdateProvider(
>   ProviderBase<Object?> provider,
>   Object? previousValue,
>   Object? newValue,
>   ProviderContainer container,
> ) {
>   if (newValue is AsyncError) {  // handle this special case
>     return _handleError(
>       provider,
>       newValue.error,
>       newValue.stackTrace,
>     );
>   }
> 
>   _logger  // "normal" logging logic
>     ..finest('$provider updated')
>     ..finest('\tOld value: $previousValue')
>     ..finest('\tNew value: $newValue');
> }
> 
> @override
> void providerDidFail(
>   ProviderBase<Object?> provider,
>   Object error,
>   StackTrace stackTrace,
>   ProviderContainer container,
> ) {
>   _handleError(provider, error, stackTrace);
> }
> 
> // or your custom logic here
> void _handleError(
>   ProviderBase<Object?> provider,
>   Object error,
>   StackTrace stackTrace,
> ) {
>   _logger
>     ..severe('$provider raised an Exception')
>     ..severe('\tError: $error')
>     ..severe('\tStack Trace: $stackTrace');
> }
> ```

Ah that's great, thank you!

**Comment by rrousselGit** [comment]
Note that this is planned for the 3.0.0.

It's a bit breaking, so that's why it waited.

**Comment by blake116th** [comment]
@rrousselGit 
Since this isn't planned til 3.0.0, it might be a good idea to update the documentation of providerDidFail in the meantime to suggest that FutureProviders won't emit events.

Per the current [API docs](https://pub.dev/documentation/riverpod/latest/riverpod/ProviderObserver/providerDidFail.html):


> void providerDidFail(...) 
> A provider emitted an error, be it by throwing during initialization or by having a Future/Stream emit an error

**Comment by rrousselGit** [comment]
This was implemented in a non-breaking way and will be available in the next stable release
