### ISSUE TITLE
overrideWith does not allow you to mock repositories, regression since overrideWithProvider

### ISSUE THREAD

**Issue by kenNg1** [rrousselGit/riverpod#1867]
Previously, I was able to mock repository calls for `overrideWithProvider` with mockito `when`, however, since upgrading to Riverpod 2.1.1 and using the new syntax `overrideWith` in some cases it doesn't respect the `when` calls. This caused quite a number of tests to fail.

Left is old, right is new syntax:
![image](https://user-images.githubusercontent.com/25297786/199532525-c46f06f5-87e5-4dae-b5fc-5887a29abd31.png)

`overrideWithProvider` has some detailed information about how to replacing a service with a fake implementation, however, I am not sure why exactly `overrideWith` sometimes does not respond to the `.when`. Would you be able to provide some advice/examples of the recommended way to test using `overrideWith` 

![image](https://user-images.githubusercontent.com/25297786/199542027-a2776fce-52d1-4295-9e32-01fa527c7b37.png)

Much appreciated

**Comment by rrousselGit** [comment]
It's not a regression, but rather your refactoring is incorrect. Your old vs new don't match.

You might want to change your mock definition to:


```dart
MyNotifierMock createNotifierMock(Ref ref) {
  return MyNotifier();
}
```

Then used as

```dart
overrides: [provider.overrideWith(createNotifierMock)]
```


Alternatively, instead of `setupAll` you could use `setup` for creating your notifier.

> overrideWithProvider has some detailed information about how to replacing a service with a fake implementation, however, I am not sure why exactly overrideWith sometimes does not respond to the .when. Would you be able to provide some advice/examples of the recommended way to test using overrideWith

`overrideWith` has a similar documentation. That's what the `@macro` is. If you hover `overrideWith`, your IDE should show you the documentation
