### ISSUE TITLE
Compile-time safety claim mismatch

### ISSUE THREAD

**Issue by purplenoodlesoop** [rrousselGit/riverpod#1973]
Hello! I was reading the documentation and examples and found a mismatch. 

The documentation claims that Riverpod is compile-time safe, but [some of the examples](https://github.com/rrousselGit/riverpod/blob/master/examples/marvel/lib/src/screens/character_detail.dart#L22) use the `UnimplementedError` to set a non-nullable type. This code can blow up and is not compile-time safe.

Is there any way to use Riverpod with compile-time safety when some kind of initial value should be passed without prop-drilling and using the `family` modifier?

**Comment by TimWhiting** [comment]
I've also thought that maybe this might not be the most appropriate claim.

I think the main concept that Remi has talked about when he mentions compile-time safety is that you only have to put the `ProviderScope` at the top - you can specify all of the dependency injection things outside the widget tree.

Your logic can always blow up, easy - just throw an Error. But the lookup of the provider doesn't error, unless you are using it wrong.

I agree however, that this should be made more clear in the documentation, and might not be best advertised as 'compile-time safety'. 

> Is there any way to use Riverpod with compile-time safety when some kind of initial value should be passed without prop-drilling and using the family modifier?

Depends on what an appropriate default / initial value could be. If so yes, just provide the default / initial value. However the whole point for the `UnimplementedError` in the example is that a default value would mean that you were using the provider wrong. In fact the `UnimplementedError` is more safe than a default value, because it would be a logical error to default to something when the other providers expect that the provider with the `UnimplementedError` must be overridden for part of the widget tree that uses it. Which is clearly explained by the documentation of that particular provider that you linked to:
```
/// It is an error to use [CharacterView] without overriding this
/// provider to a non-null value.
```

So if you are going to throw an Error, yes that error will happen at runtime, but it is up to the architect of the app whether it is better to throw at runtime, how to prevent the app from getting to that state at runtime, and if it is possible to get to that state at runtime, what an appropriate default should be, and handle that default case explicitly.

**Comment by rrousselGit** [comment]
> Is there any way to use Riverpod with compile-time safety when some kind of initial value should be passed without prop-drilling and using the family modifier?


You're free to return anything else instead. Like `null`.  
If that's what you want, go ahead. It's possible

**Comment by rrousselGit** [comment]
In this end, Riverpod isn't what's throwing in those examples. It's your logic.    
Your logic can be anything you want.

It's also a very niche use case. Using scopes to avoid props drilling is considered an advanced topic and generally best avoided unless you know what you're doing.      


In the end, the vast majority of your interactions with Riverpod fit the "compile safe" mantra.  
- If you delete a provider, consumers will have a compile error
- if you change the type of the value of a provider, you also get an error
- if you refactor from sync to async, another error
- if you try to use an autoDispose provider inside a non-autoDispsoe provider, yet another error
- if you use async logic, your UI is pushed to use `AsyncValue.when` to force the error/loading handling

There's very clearly a trend of pushing compile safety.


Yes, there are some edge cases, like that scoping usage. But that's pretty minor.
