### ISSUE TITLE
NoSuchMethodError: Class 'AsyncLoading<T>' has no instance getter 'valueOrNull'

### ISSUE THREAD

**Issue by choim4389** [rrousselGit/riverpod#2183]
**Describe the bug**

**riverpod version : flutter_riverpod 2.2.0**
In listener of `ref.listenManual`, using `next?.valueOrNull` cause `NoSuchMethodError: Class 'AsyncLoading<T>' has no instance getter 'valueOrNull'.` (yes, next is actually `AsyncLoading`)

It only seems to happen when using `ref.listenManual`. `ref.listen` in `build()` is no problem.

**To Reproduce**
Try to access `AsyncLoading.valueOrNull` in `ref.listenManual`

**Expected behavior**
`valueOrNull `must also be accessible in ref.listenManual

**Comment by rrousselGit** [comment]
Could you share a complete sample? Not sure how you ended up facing this.

**Comment by rrousselGit** [comment]
Closing in the lack of a reply

**Comment by Randomguy01** [comment]
I have a similar issue. 

Sample:
```dart
void main() {
  AsyncData asyncData1 = AsyncData([]);
  AsyncData asyncData2 = AsyncData([]);

  print(asyncData1 == asyncData2);
}
```

If you go into the == operator for AsyncValue:
```dart
  @override
  bool operator ==(Object other) {
    return runtimeType == other.runtimeType &&
        other is AsyncValue<T> &&
        other.isLoading == isLoading &&
        other.hasValue == hasValue &&
        other.error == error &&
        other.stackTrace == stackTrace &&
        other.valueOrNull == valueOrNull;
  }
```

Evaluating `other.valueOrNull` throws:
`NoSuchMethodError: Class 'AsyncData<dynamic>' has no instance getter 'valueOrNull'.`

My particular use case is testing providers. When I try to use `verify` it always fails when trying to compare AsyncData even with identical information. I am guessing this issue is causing `verify` to fail in my tests.
