### ISSUE TITLE
CORS error on the pub.dev example

### ISSUE THREAD

**Issue by rrousselGit** [rrousselGit/riverpod#2218]

**Comment by PapiHack** [comment]
Hello @rrousselGit, i hope you're doing well.
I wanted to take this issue but it seems like the examples/pub works well on my side when i launch it.
Can i have more infos about this if possible please ?
Thanks in advance.

**Comment by rrousselGit** [comment]
Have you ran the example on web?

**Comment by PapiHack** [comment]
Nope, i ran the example on an android emulator

**Comment by PapiHack** [comment]
I see the problem, thanks.
Hum, for now, Since we don't have control over the server side in order to specify the hosts authorized to make requests, the solution I propose is to use the following command `flutter run -d chrome --web-browser-flag "--disable-web-security"` which fix the issue.
Otherwise, the other option would be to use a proxy but this will need some extra code in the example.

**Comment by rrousselGit** [comment]
Indeed. But we could make a proxy to fix this issue

**Comment by PapiHack** [comment]
Hum, right.
Got it, i'll try to propose something.
Thanks.
