### ISSUE TITLE
Scoped provider with dependencies rebuilds unexpectedly

### ISSUE THREAD

**Issue by josh-burton** [rrousselGit/riverpod#2383]
**Describe the bug**
This may be a bug or maybe just behaviour I don't understand.

I have a provider that should be scoped to a route. I'm using GoRouter. 

This `scopedProvider` depends on a `tokenProvider` I inject into a ProviderScope when the page/route is created:

```
  GoRoute(
              path: "bug",
              pageBuilder: (context, state) {
                return NoTransitionPage(
                  key: state.pageKey,

                  // create a provider scope with the token value extracted from the url
                  child: ProviderScope(
                    overrides: [
                      tokenProvider.overrideWithValue("value from url"),
                    ],
                    child: MyPage(
                    ),
                  ),
                );
              },
            ),
            
            ...
// My scoped provider that depends on the overridden token provider
final scopedProvider = Provider<String>((ref) {
  return random.nextInt(100).toString();
}, dependencies: [
  tokenProvider,
]);
              
```

**Expected behavior**

The behaviour I would expect here, is that no matter if GoRouter recreates the route, as long as my tokenProvider doesn't change the `scopedProvider` should not be rebuilt.

The behaviour I am seeing is that `scopedProvider` is rebuilt whenever GoRouter rebuilds the route. 

If I change my `scopedProvider` to no longer depend on the `tokenProvider`, and instead use a family then the `scopedProvider` is no longer recreated when the route is rebuilt.

I have tried giving ProviderScope a key but this doesn't change anything.

So 2 questions:
* is this expected behaviour?
* how can I ensure my ProviderScope/scopedProvider doesn't get recreated?

**To Reproduce**

Sample with tests: https://github.com/josh-burton/riverpod_gorouter_providerscope_bug
This sample contains 2 tests, one that passes and one that fails. The difference in the tests is the one that fails has a scoped provider with dependencies.

**Comment by rrousselGit** [comment]
:wave:

Took a while for me to look into this issue, sorry.
Anyway, this is expected.

Scoped providers are, well, scoped to the associated tree.

So when a subtree is unmounted, the associated scoped providers are destroyed. And when it is remounted again, the scoped providers are recreated.

The issue here is therefore not that go_router rebuilt the page. But that when pressing the back button, the page is destroyed.
The thing is,  your `buggyProvider` is scoped to that route. It is scoped because of "dependencies". When specifying "dependencies", providers are scoped alongside their dependencies. Therefore it's all "normal".


`family` bypasses this because it does **not** rely on scoping.


My assumption is that you're effectively looking for a way to use `family` without having to specify the argument everywhere.
In that case, you're likely looking for the following feature: https://github.com/rrousselGit/riverpod/issues/767

As it is, everything works fine

**Comment by josh-burton** [comment]
Thanks for the explanation :)
