### ISSUE TITLE
Configurable generated code location

### ISSUE THREAD

**Issue by amevee** [rrousselGit/riverpod#2463]
Can we specify location of generated code?

**Comment by rrousselGit** [comment]
That's not something I care about nor the responsibility of Riverpod.

If there's such an option, it's the responsibility of build_runner. I'd suggest looking there :)

**Comment by amevee** [comment]
For someone looking for similar, you can use `build_extensions` inside `source_gen:combining_builder:`.

      source_gen:combining_builder:
        options:
          build_extensions:
            '{{dir}}/{{file}}.provider.dart': '{{dir}}/riverpodgen/{{file}}.provider.g.dart'

For more advance grouping options you can refer this - https://github.com/dart-lang/build/blob/master/docs/writing_a_builder.md#configuring-outputs

This is because riverpod generator uses source_gen and options passed to riverpod generator won't go directly to source_gen.

Also, as an additional tip, to have you builds faster you can have `generate_for` inside riverpod_generator so it don't analyse all dart files.

**Comment by Anushi1998** [comment]
For someone looking for similar, you can use `build_extensions` inside `source_gen:combining_builder:`.

      source_gen:combining_builder:
        options:
          build_extensions:
            '{{dir}}/{{file}}.provider.dart': '{{dir}}/riverpodgen/{{file}}.provider.g.dart'

For other grouping options you can refer this - https://github.com/dart-lang/build/blob/master/docs/writing_a_builder.md#configuring-outputs

This is because riverpod generator uses source_gen and options passed to riverpod generator won't go directly to source_gen.

Also, as an additional tip, to have you builds faster you can have `generate_for` inside riverpod_generator so it don't analyse all dart files.
