### ISSUE TITLE
No docs for @Riverpod(keepAlive: true)

### ISSUE THREAD

**Issue by akarabach** [rrousselGit/riverpod#2524]
No docs that `@reverpod` is `keepAlive: false` by default. There is no docs about `@Riverpod` at all. I have found issue here where I  found out about `@Riverpod()`

**Comment by kwilliams3** [comment]
I'm wondering if the `@riverpod` annotation should be removed entirely. Perhaps I'm not aware of a convention out there, but it seems like `@Riverpod()` with no arguments works just fine and it might avoid confusion as to why there's two riverpod annotations and which one should be used when. Since `@riverpod` is the same as `@Riverpod()`, I'm not sure the code simplification is worth the potential for confusion.

If we do want to keep `@riverpod`, perhaps we can update the documentation like this:

>If you don't want your provider to be automatically disposed (i.e. - `.autodispose`), you can use the `@Riverpod` annotation with `keepAlive: true`. 
```
@Riverpod(keepAlive: true)
ReusableObject getReusableObject(FetchUserRef ref) {
  return ReusableObject();
}
```

We can put this on the Code Generation page just above the sentence "When using Riverpod, code generation is completely optional. It is entirely possible to use Riverpod without."
>>>

**Comment by rrousselGit** [comment]
@akarabach The [code-gen page](https://docs-v2.riverpod.dev/docs/about_code_generation) says that the following snippets are equivalent:

 
<img width="986" alt="Screenshot 2023-05-04 at 20 36 39" src="https://user-images.githubusercontent.com/20165741/236297661-7d7d91f7-ede0-421a-8bc4-24cf697ad63a.png">

**Comment by rrousselGit** [comment]
@kwilliams3 This seems unrelated to the topic at hand.

I haven't seen anyone getting confused by this. It's a fairly common pattern. You'd find the same in freezed and functional_widget for instance

**Comment by kwilliams3** [comment]
> @kwilliams3 This seems unrelated to the topic at hand.
> 
> I haven't seen anyone getting confused by this. It's a fairly common pattern. You'd find the same in freezed and functional_widget for instance

Perfect 👍 I figured there probably was a convention I didn't know about. Thanks for the insight!

**Comment by kwilliams3** [comment]
> @akarabach The [code-gen page](https://docs-v2.riverpod.dev/docs/about_code_generation) says that the following snippets are equivalent:
> 
> <img alt="Screenshot 2023-05-04 at 20 36 39" width="986" src="https://user-images.githubusercontent.com/20165741/236297661-7d7d91f7-ede0-421a-8bc4-24cf697ad63a.png">

I think @akarabach is saying that since autodispose is not the default when creating a provider (need to manually add `.autodispose`), one might naively expect that `@riverpod` would have `keepAlive: true` by default and only autodispose when explicitly specified.

Additionally, turning on or off autodispose via annotations isn't documented yet. Some people are not sure how to do it: https://stackoverflow.com/questions/74123229/how-to-prevent-provider-from-auto-disposing-when-using-riverpod-generator

**Comment by rrousselGit** [comment]
That's in part because not all docs pages are updated. 

https://docs-v2.riverpod.dev/docs/concepts/modifiers/auto_dispose should be migrated to codegen.

**Comment by kwilliams3** [comment]
Ah, that makes sense. So, you would just use [ref.keepAlive](https://docs-v2.riverpod.dev/docs/concepts/modifiers/auto_dispose#refkeepalive) in your function to achieve the same effect as `@Riverpod(keepAlive: true)`, correct?

**Comment by rrousselGit** [comment]
No, `Riverpod(keepAlive:true)` is still the proper way if possible

**Comment by rich-j** [comment]
Minor point - the above `fetchUserProvider` snippets are actually not "equivalent" since `userId` is a `String` in the first one and an `int` in the second  :slightly_smiling_face:

**Comment by akarabach** [comment]
>I think @akarabach is saying that since autodispose is not the default when creating a provider (need to manually add .autodispose), one might naively expect that @riverpod would have keepAlive: true by default and only autodispose when explicitly specified.

Exactly, I would prefer `keepAlive: true` by default. I back to the project after one year and was migrating all providers to new approach and did not expect it by default.

**Comment by kwilliams3** [comment]
@rich-j Thanks for pointing it out. There's a PR to address it now (#2533).

**Comment by kwilliams3** [comment]
> > I think @akarabach is saying that since autodispose is not the default when creating a provider (need to manually add .autodispose), one might naively expect that @riverpod would have keepAlive: true by default and only autodispose when explicitly specified.
> 
> Exactly, I would prefer `keepAlive: true` by default. I back to the project after one year and was migrating all providers to new approach and did not expect `autodispose` by default.

Moving this proposal into a separate discussion in order to keep the conversation within this issue strictly about the desire for additional documentation. Please reference #2534 to follow along with / participate in the discussion.

**Comment by rrousselGit** [comment]
Moving the tracking for this to https://github.com/rrousselGit/riverpod/issues/2631
