### ISSUE TITLE
Endless AsyncLoading when watching future family providers

### ISSUE THREAD

**Issue by AAverin** [rrousselGit/riverpod#2693]
**Describe the bug**
Watching Future provider and doing data post processing via AsyncValue results in endless AsyncLoading

**To Reproduce**

```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter/src/widgets/framework.dart';
import 'package:hooks_riverpod/hooks_riverpod.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';

part 'TestScreen.g.dart';

@riverpod
Future<int> counter(CounterRef ref, int param) async => param;

@riverpod
Future<int> counterPlus1(CounterPlus1Ref ref, int param) async {
  return (await ref.watch(counterProvider(param).future)) + param;
}

@riverpod
Future<int> counterPlus2(CounterPlus2Ref ref, int param) async {
  final counter = await ref.watch(counterProvider(param).future);
  final counterPlus1 = ref.watch(counterPlus1Provider(param));
  return counterPlus1.when(
      data: (data) => data + counter, error: (e, s) => 0, loading: () => 0);
}

class TestScreen extends HookConsumerWidget {
  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return Scaffold(
      body: Consumer(builder: (context, ref, _) {
        return ref.watch(counterPlus2Provider(5)).when(
            data: (d) => Text("data $d"),
            error: (_, __) => Text("Error"),
            loading: () => Text("Loading"));
      }),
    );
  }
}
```

**Expected behavior**
Data correctly displayed after loading

**Comment by rrousselGit** [comment]
If my understanding of the issue is correct, that's "expected".

You should either use only `ref.watch(futureProvider.future)` or `ref.watch(futureProvider).when(...)`

Miking them means they have two different loading handling. Combined with autoDispose, that gets weird.

The issue is that when you do:

```dart
@riverpod
Future<int> counterPlus2(CounterPlus2Ref ref, int param) async {
  final counter = await ref.watch(counterProvider(param).future);
  final counterPlus1 = ref.watch(counterPlus1Provider(param));

```` 

then while "counterProvider` is "awaited", counterPlus1Provider isn't listened. So it gets disposed.
Therefore it enters a loading on next read.
Then when loaded, it refreshes counterProvider, which retriggers the await, which dispose counterPlus1Provider  once again for the same reason.


That wouldn't happen if you used a consistent loading approach.


A workaround is to change the order in which providers are read:

```dart
@riverpod
Future<int> counterPlus2(CounterPlus2Ref ref, int param) async {
   final counterPlus1 = ref.watch(counterPlus1Provider(param));
  final counter = await ref.watch(counterProvider(param).future);
```

This fixes the issue, because now while counterProvider is awaited, counterPlus1  is still listened. So it does _not_ get disposed.

There's a more specific feature request to better deal with this, but that's a breaking change. https://github.com/rrousselGit/riverpod/issues/1253
So it won't come before 3.0
