### ISSUE TITLE
Why abstract class ConsumerWidget extends ConsumerStatefulWidget { ?

### ISSUE THREAD

**Issue by awaik** [rrousselGit/riverpod#2917]
Thank you for the great package, we are using it in production and it works great.

This is just a question out of curiosity, why `abstract class ConsumerWidget extends ConsumerStatefulWidget {`?

I thought it should extends Stateless widget?

And one more theoretical question, we are using internalisation and every widget has to contain

`final t = state.ref.watch(localeStateProvider.select((value) => value.translations));`

What is the correct way to create wrapper for this use case for `ConsumerWidget` and `ConsumerStatefulWidget`?

**Comment by lonelyteapot** [comment]
Hello! I'm not an author of Riverpod, but here are my thoughts.

---

> Why `abstract class ConsumerWidget extends ConsumerStatefulWidget {`?

I think it's because any consumer widget implicitly has state. Just instead of defining its own, it depends on external state from providers. To handle that state, internally a ConsumerWidget has to be able to listen to changes, react by triggering rebuilds and alert of its disposal. `StatelessWidget` is not designed for these dynamic behaviors.

---

> What is the correct way to create wrapper for this use case for `ConsumerWidget` and `ConsumerStatefulWidget`?

You can extend `ConsumerState` class to define a custom property:

```dart
abstract class TranslatableConsumerState<T extends ConsumerStatefulWidget> extends ConsumerState<T> {
  TranslationsType get t => ref.watch(localeStateProvider.select((value) => value.translations));
}
```

...and then use the extended class for `ConsumerStatefulWidget`s instead of the original:

```dart
class _FooWidget extends ConsumerStatefulWidget {
  @override
  TranslatableConsumerState<_FooWidget> createState() => _FooWidgetState();
}

class _FooWidgetState extends TranslatableConsumerState<_FooWidget> {
  @override
  Widget build(BuildContext context) {
    // `t` is available here
    throw UnimplementedError();
  }
}
```

This solution can be further simplified if you want this behavior for _all_ consumer widgets in the project. Instead, define an `extension` on `ConsumerState` and use it as usual. These solutions are functionally identical.

```dart
extension TranslatableConsumerState on ConsumerState {
  TranslationsType get t => ref.watch(localeStateProvider.select((value) => value.translations));
}
```

_Note that to use the extension, you still have to import its source file (autocomplete can usually do it)._ 

Not sure if this can be easily achieved with a "stateless" `ConsumerWidget`. One idea is to define an extension on `WidgetRef` to use it like `ref.t`.

---

Also, perhaps this question is better suited for the [Discussions](https://github.com/rrousselGit/riverpod/discussions) section rather than Issues.

**Comment by rrousselGit** [comment]
The reason is more boring than you'd expect:

It's because `StatelessWidget` already has a `build(context)` method. But Riverpod wants a `build(context, ref)`.
Those functions aren't compatible with each-other.
By subclassing StatefulWidget instead, Riverpod can have `ConsumerWidget.build` receive two parameters instead of one.

**Comment by awaik** [comment]
Thanks guys!
