### ISSUE TITLE
Improve DO/DON'T session

### ISSUE THREAD

**Issue by quangson91** [rrousselGit/riverpod#3014]
**Describe what scenario you think is uncovered by the existing examples/articles**
In `DO/DON'T` session, I think it should better if there is both DO/DON'T for each example.

**Describe why existing examples/articles do not cover this case**
For example:

## AVOID having to intialize providers in a widget

**DON'T**

```
class WidgetState extends State<MyWidget> {
  @override
  void initState() {
    super.initState();
    // Bad: the provider should initialize itself
    ref.read(provider).init();
  }
}
```

But it should better to tell user what is the `DO` right way for that.

**Additional context**
Add any other context or screenshots about the documentation request here.

**Comment by rrousselGit** [comment]
It's not uncommon to not have a clearcut solution. There may be many competing solutions to the same problem, based on whatever your scenario is.  
For instance, passing arguments to the provider, initializing it in an `onPressed`, or having the init logic in the provider itself.

Since there's no clear answer, there's only an "avoid" mention.

Kind of like a lint rule. Just because a linter knows what you shouldn't do doesn't mean the linter knows what you should do :)

**Comment by rrousselGit** [comment]
But if you have more specific suggestions, I'm more than happy to include them in the docs.
At it is, I don't think I'd realistically be able to add much

**Comment by quangson91** [comment]
@rrousselGit 
Thank you for the fast reply.
I would like to know about this case: `or having the init logic in the provider itself.`

In the `DON'T` example:

```
class WidgetState extends State<MyWidget> {
  @override
  void initState() {
    super.initState();
    // Bad: the provider should initialize itself
    ref.read(provider).init();
  }
}
```

It looks like call `init` something once when this widget created.

So, what is an equivalent for `init` in the provider. (Eg usecase, perforce some logic when this user open the screen first time).

In android, if I use ViewModel, I can do it in the `init` block.
Example:

```
class MyViewModel : ViewModel() {
    init {
        // Do something here when this view model init. It do only one time.
    }

}
```
