### ISSUE TITLE
Notifiers should not have public properties/getters. Instead, all their public API should be exposed through the `state` property.

### ISSUE THREAD

**Issue by hcanyz** [rrousselGit/riverpod#3128]
**Describe the bug**
I got a warning when creating the Provider.

![image](https://github.com/rrousselGit/riverpod/assets/8407922/8026a5fd-a89c-49c8-9fdd-2df78d754d3f)

**To Reproduce**

```dart
import 'package:riverpod_annotation/riverpod_annotation.dart';

part 'main.g.dart';

@riverpod
class LintTest extends _$LintTest {
  @override
  String build() => "";

  String get get => state; // warning 

  String method() => state;
}

```

**Expected behavior**

```get``` only uses state, which is reasonable and requires no warning, just like ```method```.

**Comment by rrousselGit** [comment]
Nope it isn't :)

No public getter/properties

**Comment by sharpsan** [comment]
Would you mind elaborating on _why_ getters are not reasonable?  Thanks in advance.

**Comment by kwikwag** [comment]
My two cents - a provider is a memoized function. Why would you want getters on memoized functions? You probably want the getter on the value that the provider builds. That is, instead of returning a string, you can return an object with a getter. Or some other model with getters, depending on your use case. Refer to the [documentation](https://pub.dev/packages/riverpod_lint#avoid_public_notifier_properties).

For future reference, it's always good to include a use case rather than a contrived example.
