### ISSUE TITLE
[quality of life] make `riverpod_annotation` re-export utilities such as `@protected`

### ISSUE THREAD

**Issue by lucavenir** [rrousselGit/riverpod#3495]
**Is your feature request related to a problem? Please describe.**
More often than not I write notifiers like the following

```dart
import 'package:freezed_annotation/freezed_annotation.dart'; // !

class MyNotifier extends _$MyNotifier {
  @protected  // love it
  @visibleForTesting  // love it
  late MyApi myApi;

  Future<int> build() {
    myApi = ref.watch(myApiProvider);
    return myApi.get();
  }
  
  Future<void> increment() {
    return update(
      (state) => myApi.incrementFrom(state),
    );
  }
}
```

Which I do since I want my dependencies to be protected but testable.

**Describe the solution you'd like**
It's just weird that I have to import `freezed_annotation` or `flutter:foundation` just to use the above annotations. I'd expect riverpod to offer this because of how handy tests become via these annotations.

**Describe alternatives you've considered**
Maybe I *shouldn't* protect my dependencies like so, and tests should be done in another way?
Either way, it's not too big of a deal.

**Are you able to PR this one?**
Yes I could if approved.

**Comment by rrousselGit** [comment]
Freezed shouldn't be exporting those annotations. I'd remove those in a future release

I don't want packages to export things that are not coming from said package.  
The only reason some transitive dependencies are re-exported by the annotation package is because the generated code uses it.

Once we have metaprogramming (and therefore when generated code will be able to define imports on its own), my annotation packages will never export other packages.

**Comment by lucavenir** [comment]
Sorry then, I totally misunderstood the purpose of these re-exports.
Fine then, I'll just import `flutter/foundation` x)
