### ISSUE TITLE
updateOverrides with provider.overrideWith does not seem to work

### ISSUE THREAD

**Issue by woprandi** [rrousselGit/riverpod#3819]
**Describe the bug**
`ProviderContainer.updateOverrides` does not seem to work with `overrideWith` (with neither sync not async provider)

**To Reproduce**

```dart
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  final myProvider1 = Provider((a) => "provider 1");
  final myProvider2 = Provider((a) => "provider 2");

  test('test', () async {
    final container = ProviderContainer(
      overrides: [
        myProvider1.overrideWithValue("override 1"),
        myProvider2.overrideWith((_) => "override 1")
      ],
    );

    var value1 = container.read(myProvider1);
    var value2 = container.read(myProvider2);
    expect(value1, "override 1");
    expect(value2, "override 1");

    container.updateOverrides([
      myProvider1.overrideWithValue("override 2"),
      myProvider2.overrideWith((_) => "override 2"),
    ]);

    await container.pump();
    value1 =  container.read(myProvider1);
    value2 =  container.read(myProvider2);
    expect(value1, "override 2");
    expect(value2, "override 2"); // does not pass
  });
}

```
**Expected behavior**

`overrideWith` should work with `updateOverrides`

Tester with latest riverpod 2.6.1

**Comment by rrousselGit** [comment]
That is the expected behaviour.  The goal of `overrideWith` is to offer a behaviour similar to that of a "global" provider ; including the cache behaviour.

At the same time, we cannot detect if the callback passed was meaningfully changed or not.
ProviderScope called updateOverrides whenever the widget rebuilds. But in the context of Flutter, that's mean overrideWith would receive a new callback everytimes.
This would kill `overrideWith`'s ability to cache values.
